Update systemctl

diff --git a/systemctl b/systemctl
--- a/systemctl
+++ b/systemctl
@@ -20,6 +20,10 @@ PROGURL="https://github.com/gmt4/fake-systemd"
 
 startstopdaemon="$(command -v start-stop-daemon)"
 
+warn() {
+    >&2 echo "$@"
+}
+
 get_unit_file(){
     # Check for Alias=unit.service
     Alias=$(grep -hr "^Alias=${UNIT}" "${UNIT_PATHS[@]}" 2>/dev/null | sed -n 's/^Alias=//p')
@@ -27,7 +31,7 @@ get_unit_file(){
         UNIT="$Alias"
     fi
 
-    for dir in ${UNIT_PATHS[@]} ;
+    for dir in ${UNIT_PATHS[@]};
     do
         if [ -f "${dir}${UNIT}" ]; then
             echo "${dir}${UNIT}"
@@ -178,7 +182,7 @@ action_start(){
 
         action_eval "${ExecStartPost[@]}"
     else
-        >&2 echo "Unknown service type $Type"
+        warn "Unknown service type $Type"
     fi
 }
 
@@ -251,7 +255,7 @@ action_enable(){
     local WantedBy=$(read_option WantedBy)
 
     if [ -z "$WantedBy" ] ; then
-        >&2 echo "Unit $UNIT have no WantedBy option."
+        warn "Unit $UNIT have no WantedBy option."
         exit 1
     fi
 
@@ -268,7 +272,7 @@ action_disable(){
     local WantedBy=$(read_option WantedBy)
 
     if [ -z "$WantedBy" ] ; then
-        >&2 echo "Unit $UNIT have no WantedBy option."
+        warn "Unit $UNIT have no WantedBy option."
         exit 1
     fi
 
@@ -290,10 +294,10 @@ action_isenabled(){
         local WANTEDBY_DIR="/etc/systemd/system/$WantedBy.wants"
         if [ -f "$WANTEDBY_DIR/$UNIT_FULL" ] ; then
             echo "enabled"
-            exit 0
+            return 0
         else
             echo "disabled"
-            exit 1
+            return 1
         fi
     fi
 }
@@ -302,16 +306,15 @@ action_isactive(){
     pid=$(_get_pid)
 
     # set default pifile
-    [ "$pid" == "-1" ] && echo "unknown" && exit 3
+    [ "$pid" == "-1" ] && echo "unknown" && return 3
 
     # check if the pid exists - systemctl returns 3
-    [ -r "/proc/$pid/status" ] || kill -0 "$pid" > /dev/null 2>&1
-    if [ $? -eq 0 ]; then
+    if [ -r "/proc/$pid/status" ] || kill -0 "$pid" > /dev/null 2>&1 ; then
         echo "active"
-        exit 0
+        return 0
     else
         echo "inactive"
-        exit 3
+        return 3
     fi
 }
 
@@ -394,10 +397,10 @@ action_list_units(){
 }
 
 helper_list_units(){
-    for dir in ${UNIT_PATHS[@]} ;
+    for dir in ${UNIT_PATHS[@]};
     do
         [ -d "$dir" ] && ls -1 $dir
-    done
+    done | sort | uniq
 }
 
 exec_action(){
@@ -416,7 +419,7 @@ exec_action(){
     local UNIT_FILE="$(get_unit_file "$UNIT")"
     if [ -z "$UNIT_FILE" ] || [ ! -f "$UNIT_FILE" ]
     then
-        >&2 echo "Unit $UNIT could not be found."
+        warn "Unit $UNIT could not be found."
         return
     fi
 
@@ -444,7 +447,7 @@ exec_action(){
         show)       action_show ;;
         list-units) action_list_units;;
 
-        help ) >&2 echo "This command expects one or more unit names. Did you mean --help?" ; return ;;
+        help ) warn "This command expects one or more unit names. Did you mean --help?" ; return ;;
         -h )        usage; return 0 ;;
         --help )    usage; return 0 ;;
         # exit 0 if unknown operation to avoid errors
@@ -460,11 +463,11 @@ action_daemonreload()
 }
 
 action_unknown(){
-    >&2 echo "$PROGNAME: Warning unknown op $*"
+    warn "$PROGNAME: Warning unknown op $*"
 }
 
 action_nop(){
-    >&2 echo "$PROGNAME: Warning nop $*"
+    warn "$PROGNAME: Warning nop $*"
 }
 
 usage(){
@@ -534,7 +537,7 @@ main(){
 
     if [ -z "$startstopdaemon" ];
     then
-        >&2 echo "$PROGNAME: Error start-stop-daemon not found"
+        warn "$PROGNAME: Error start-stop-daemon not found"
     fi
 
     for UNIT in ${UNITS[@]};
