systemctl: Update systemctl help

diff --git a/systemctl b/systemctl
--- a/systemctl
+++ b/systemctl
@@ -1,5 +1,7 @@
 #!/bin/bash
 #
+# @git: https://github.com/gmt4/fake-systemd/
+#
 # upper vars:     like UNIT* are in exec_action context
 # lower vars:     in local function
 # camelcase vars: systemd params var
@@ -341,32 +343,28 @@ function exec_action(){
     local ACTION=$1
     local UNIT=$2
 
-    [[ $UNIT =~ '.' ]] || UNIT="$UNIT.service"
+    [[ "$UNIT" =~ '.' ]] || UNIT="$UNIT.service"
 
-    local UNIT_NAME=$(echo $UNIT | cut -d '.' -f1)
+    local UNIT_NAME=$(echo "$UNIT" | cut -d '.' -f1)
 
     if [[ $UNIT =~ '@' ]] ; then
         local UNIT_INSTANCE="$(echo "$UNIT" | cut -d'@' -f2- | cut -d. -f1)"
-        local UNIT="$(echo $UNIT | sed "s/$UNIT_INSTANCE//")"
+        local UNIT="$(echo "$UNIT" | sed "s/$UNIT_INSTANCE//")"
     fi
 
     local UNIT_FILE="$(get_unit_file "$UNIT")"
-    if [ ! -f "$UNIT_FILE" ]
+    if [ -z "$UNIT_FILE" ] || [ ! -f "$UNIT_FILE" ]
     then
-        echo "Unit $UNIT could not be found."
-        return
+        >&2 echo "Unit $UNIT could not be found."
+        exit 4
     fi
-    local UNIT_FULL="$(echo $UNIT | sed "s/@/@$UNIT_INSTANCE/")"
+
+    local UNIT_FULL="$(echo "$UNIT" | sed "s/@/@$UNIT_INSTANCE/")"
     local UNIT_WANTS=($(get_unit_wants "$UNIT"))
 
     # Systemd env variables
     # https://www.freedesktop.org/software/systemd/man/systemd.service.html
     local MAINPID=$(_get_pid)
-
-    if [ -z "$UNIT_FILE" ] ; then
-        >&2 echo "Failed to $ACTION $UNIT: Unit $UNIT not found."
-        exit 1
-    fi
 
     case "$ACTION" in
         status )    action_status ;;
@@ -382,7 +380,7 @@ function exec_action(){
         --help ) echo -e  "$USAGE" ; exit 0 ;;
         # exit 0 if unknown operation to avoid errors
         # like mask, unmask etc
-        * ) >&2 echo "Unknown operation '$ACTION'" ; exit 0 ;;
+        *) >&2 echo "Unknown operation $ACTION." ; exit 1 ;;
     esac
 }
 
@@ -415,17 +413,22 @@ Unit File Commands:
         /usr/lib/systemd/system/
     )
 
-    if [ -z "$UNITS" ]; then
+    if [ -z "$UNITS" ];
+    then
         case "$ACTION" in
-            '') echo -e "$USAGE" ; exit 0 ;;
-            -h ) echo -e "$USAGE" ; exit 0 ;;
-            --help ) echo -e  "$USAGE" ; exit 0 ;;
+            status|start|stop|restart|enable|disable|is-active|is-enabled) ;;
+            '')      echo -e "$USAGE" ; exit 0 ;;
+            -h)      echo -e "$USAGE" ; exit 0 ;;
+            help)    echo -e "$USAGE" ; exit 0 ;;
+            --help)  echo -e "$USAGE" ; exit 0 ;;
+            *) >&2   echo "Unknown operation $ACTION." ; exit 1 ;;
         esac
     fi
 
-    for UNIT in ${UNITS[@]}; do
+    for UNIT in ${UNITS[@]};
+    do
         exec_action $ACTION $UNIT
     done
 }
 
-main $@
+main "$@"
